Make file-cmp a stand-alone tool
 * file-cmp no longer requires output from heal-list and can be run on
   its own to produce the desired output.

diff --git a/file-cmp b/file-cmp
--- a/file-cmp
+++ b/file-cmp
@@ -12,14 +12,183 @@ die() { echo "error: $*" >&2; exit 1; }
 ## usage
 usage()
 {
-	: usage: "$@"
+	: "usage($*)"
 	if test "$#" -gt '0'; then
 		error "$*"
 		echo "try '$0 --help'" >&2
 		exit 1
 	fi
-	echo "usage: $0 <file>" >&2
+	echo "usage: $0 <volume> <node> [/path/to/backup]" >&2
 	exit 0
+}
+
+## volume_is_valid
+# @1 volume name
+volume_is_valid() { gluster volume list|grep -q "^${1}$"; }
+
+## brick_path
+# @1 volume name
+# @2 node
+# Find the brick path for a given node
+brick_path()
+{(
+	: "brick_path($*)"
+	__brick_path_volume="${1}"
+	__brick_path_node="${2}"
+	gluster volume status "${__brick_path_volume}"|while read __brick_path_line; do
+		set -- ${__brick_path_line}
+		case "${1}" in
+		(Brick*)
+			set -- "${2%%:*}" "${2#*:}"
+			if test "${1}" = "${__brick_path_node}"; then
+				echo "${2#*:}"
+				exit 0
+			fi
+			continue
+			;;
+		esac
+	done
+	exit 0
+)}
+
+## file_from_inum
+# @1 brick path
+# @2 inum
+file_from_inum()
+{
+	: "file_from_inum($*)"
+	find "${1}" -inum "${2}" ! -path '*/.glusterfs/*'|sed -e "s,^${1},,"
+}
+
+## file_from_gfid
+# @1 brick path
+# @2 gfid
+#
+# The .glusterfs directory in the brick root has files named by GFIDs.
+#   IF: The GFID identifies a directory, then this file is a symlink to the actual
+#       directory.
+#   IF: The GFID identifies a file, then this file is a hard-link to the actual file.
+file_from_gfid()
+{
+	: "file_from_gfid($*)"
+	set -- "${1}" "${2}" "${2%${2##????}}"
+	set -- "${1}" "${2}" "${1}/.glusterfs/${3%??}/${3#??}"
+	set -- "$@" "${3}/${2}"
+	# @1 brick path
+	# @2 gfid
+	# @3 gfid_prefix
+	# @4 gfid_path
+	test -e "${4}" || die "no such file or directory '${4}'"
+
+	if test -h "${4}"; then
+		! "${VERBOSE}" || printf "${2}:dir:"
+		realpath "${3}/$(readlink "${4}")"
+	else
+		set -- "$@" "$(stat --printf='%i' "${4}")"
+		# @5 inum
+		if "${VERBOSE}"; then
+			file_from_inum "${1}"  "${5}" \
+				| while read __file_from_gfid_line; do echo "${2}:file:${__file_from_gfid_line}";done
+		else
+			file_from_inum "${1}"  "${5}"
+		fi
+	fi
+}
+
+## vol_heal_list_gfid
+# @1 hostname to use for the local node
+vol_heal_list_gfid()
+{(
+	: "vol_heal_list_gfid($*)"
+	__vol_heal_list_gfid_hostname="${1}"
+	while read __vol_heal_list_gfid_line; do
+		test -n "${__vol_heal_list_gfid_line}" || continue
+		case "${__vol_heal_list_gfid_line}" in
+		(Brick*:*)
+			set -- ${__vol_heal_list_gfid_line}
+			: "__vol_heal_list_gfid_hostname='${__vol_heal_list_gfid_hostname}'"
+			: "$@"
+
+			case "${2}" in
+			(${__vol_heal_list_gfid_hostname}:*)
+				__vol_heal_list_gfid_brick="${2##*:}";;
+			(*)	__vol_heal_list_gfid_brick=
+				continue;;
+			esac
+
+			test -d "${__vol_heal_list_gfid_brick}" || die "local brick not found '${__vol_heal_list_gfid_brick}'"
+			continue
+			;;
+		esac
+
+		test -n "${__vol_heal_list_gfid_brick}" || continue
+
+		case "${__vol_heal_list_gfid_line}" in
+		(*gfid:*)
+			__vol_heal_list_gfid_head="${__vol_heal_list_gfid_line##*:}"
+			__vol_heal_list_gfid_tail="${__vol_heal_list_gfid_head#*/}"
+			if test "${__vol_heal_list_gfid_head}" != "${__vol_heal_list_gfid_tail}"; then
+				__vol_heal_list_gfid_head="${__vol_heal_list_gfid_head%${__vol_heal_list_gfid_tail}}/${__vol_heal_list_gfid_tail}"
+			else
+				__vol_heal_list_gfid_head="${__vol_heal_list_gfid_head%>}"
+			fi
+			file_from_gfid "${__vol_heal_list_gfid_brick}" "${__vol_heal_list_gfid_head}"
+			;;
+
+		(Status:*|Number*of*entries:*)
+			continue;;
+
+		(*)	printf '%s\n' "${__vol_heal_list_gfid_line}";;
+		esac
+	done
+)}
+
+## file_cmp
+# @1 /path/to/local/brick
+# @2 host:/path/to/remote/brick
+# @3 optional /path/to/backup
+file_cmp()
+{
+	: "file_cmp($*)"
+	__file_cmp_local_path="${1}"
+	__file_cmp_remote_host="${2%%:*}"
+	__file_cmp_remote_path="${2#*:}"
+	__file_cmp_backup_path="${3}"
+
+	while read __file_cmp_line; do
+		__file_cmp_backup_size=0
+		__file_cmp_remote_size=0
+		if ! __file_cmp_local_size="$(stat --printf='%s' "${__file_cmp_local_path}${__file_cmp_line}")"; then
+			test -e "${__file_cmp_backup_path}${__file_cmp_line}" || die "invalid file '${__file_cmp_line}'"
+			__file_cmp_local_size=0
+		fi
+		if test -e "${__file_cmp_backup_path}${__file_cmp_line}"; then
+			__file_cmp_backup_size="$(stat --printf='%s' "${__file_cmp_backup_path}${__file_cmp_line}")"
+		fi
+		if ! rtest "${__file_cmp_remote_host}" -e "\"${__file_cmp_remote_path}${__file_cmp_line}\""; then
+			__file_cmp_remote_size=0
+		else
+			__file_cmp_remote_size="$(rstat "${__file_cmp_remote_host}" --printf='%s' "\"${__file_cmp_remote_path}${__file_cmp_line}\"")" || :
+		fi
+		if test "${__file_cmp_local_size}" -eq "${__file_cmp_remote_size}"; then
+			if test "${__file_cmp_local_size}" -gt '0'; then
+				! ${VERBOSE} || echo "OK:${__file_cmp_line}"
+			else
+				! ${VERBOSE} || echo "!:${__file_cmp_line}"
+				continue
+			fi
+		elif test "${__file_cmp_local_size}" -gt "${__file_cmp_remote_size}"; then
+			! ${VERBOSE} || printf '%d>%d:%s\n' "${__file_cmp_local_size}" "${__file_cmp_remote_size}" "${__file_cmp_line}"
+		elif test "${__file_cmp_backup_size}" -gt "${__file_cmp_remote_size}"; then
+			! ${VERBOSE} || printf '%d>%d:%s\n' "${__file_cmp_local_size}" "${__file_cmp_remote_size}" "${__file_cmp_line}"
+		else
+			! ${VERBOSE} || printf '%d<%d:%s\n' "${__file_cmp_local_size}" "${__file_cmp_remote_size}" "${__file_cmp_line}"
+		fi
+	done
+	unset __file_cmp_local_path
+	unset __file_cmp_remote_host
+	unset __file_cmp_remote_path
+	unset __file_cmp_backup_path
 }
 
 ## rtest
@@ -27,14 +196,16 @@ usage()
 # ... args to remote test
 rtest()
 {
-	: rtest: "$@"
+	: "rtest($*)"
+	__rtest_remote_host="${1}"
 	shift
-	set -- $(ssh -n "${REMOTE_HOST}" "STRING_ERR=\"\$(test "$@" 2>&1 1>/dev/null)\";echo \"\$? \${STRING_ERR}\"")
-	rtest_return="${1}"
+	set -- $(ssh -n -T -o PasswordAuthentication=no "${__rtest_remote_host}" "STRING_ERR=\"\$(test "$@" 2>&1 1>/dev/null)\";echo \"\$? \${STRING_ERR}\"")
+	__rtest_return="${1}"
 	shift 1
 	test "$#" -eq 0 || echo "$*" >&2
-	set -- ${rtest_return}
-	unset rtest_return
+	set -- ${__rtest_return}
+	unset __rtest_remote_host
+	unset __rtest_return
 	return $1
 }
 
@@ -43,59 +214,56 @@ rtest()
 # ... args to remote stat
 rstat()
 {
-	: rstat: "$@"
+	: "rstat($*)"
+	__rstat_remote_host="${1}"
 	shift
-	set -- $(ssh -n "${REMOTE_HOST}" "STRING_OUT=\"\$(stat "$@" 2>/dev/null)\";printf \"\$? \${STRING_OUT}\"")
-	rstat_return="${1}"
+	set -- $(ssh -n -T -o PasswordAuthentication=no "${__rstat_remote_host}" "STRING_OUT=\"\$(stat "$@" 2>/dev/null)\";printf \"\$? \${STRING_OUT}\"")
+	__rstat_return="${1}"
 	shift 1
 	echo "$*"
-	set -- ${rstat_return}
-	unset rstat_return
+	set -- ${__rstat_return}
+	unset __rstat_remote_host
+	unset __rstat_return
 	return $1
 }
 
-LOCAL_PREFIX='/srv/gluster/brick1-3/volume'
-REMOTE_PREFIX='/srv/gluster/brick1-3/volume'
-BACKUP_PREFIX='/srv/backup/brick1-3/volume'
-REMOTE_HOST='node1'
-VERBOSE=true
+
+
+# Argument handling
+VERBOSE='false'
+for arg; do case "${arg}" in (-h|--help) usage;;esac;done
+while test "$#" -gt "0"; do
+	case "${1}" in
+	(-H|--hostname)	HOSTNAME="${2}";shift 2;;
+	(-v|--verbose)	VERBOSE='true';shift;;
+	# Basic posix conformance
+	(-*)	usage "unknown argument '${1}'";;
+	(--)	shift; break;; # Start parsing on '--'
+	(*)	break;;	# Break on unknown arguments
+	esac
+done
 export VERBOSE
 
-test "$#" -gt 0 || usage 'no file specified'
+test -n "${HOSTNAME}" || HOSTNAME="$(hostname)"
+export HOSTNAME
 
-for FILE; do test -f "${FILE}" || usage "no such file '${FILE}'"; done
-for FILE; do
-	LINENO=0
-	while read LINE; do
-		LINENO="$((${LINENO}+1))"
-		: "${LINE}:${LINENO}"
-		backup_size=0
-		remote_size=0
-		if ! local_size="$(stat --printf='%s' "${LOCAL_PREFIX}${LINE}")"; then
-			test -e "${BACKUP_PREFIX}${LINE}" || die "invalid file '${LINE}'"
-			local_size=0
-		fi
-		if test -e "${BACKUP_PREFIX}${LINE}"; then
-			backup_size="$(stat --printf='%s' "${BACKUP_PREFIX}${LINE}")"
-		fi
-		if ! rtest "${REMOTE_HOST}" -e "\"${REMOTE_PREFIX}${LINE}\""; then
-			remote_size=0
-		else
-			remote_size="$(rstat "${REMOTE_HOST}" --printf='%s' "\"${REMOTE_PREFIX}${LINE}\"")" || :
-		fi
-		if test "${local_size}" -eq "${remote_size}"; then
-			if test "${local_size}" -gt '0'; then
-				! ${VERBOSE} || echo "OK:${LINE}"
-			else
-				! ${VERBOSE} || echo "!:${LINE}"
-				continue
-			fi
-		elif test "${local_size}" -gt "${remote_size}"; then
-			! ${VERBOSE} || printf '%d>%d:%s\n' "${local_size}" "${remote_size}" "${LINE}"
-		elif test "${backup_size}" -gt "${remote_size}"; then
-			! ${VERBOSE} || printf '%d>%d:%s\n' "${local_size}" "${remote_size}" "${LINE}"
-		else
-			! ${VERBOSE} || printf '%d<%d:%s\n' "${local_size}" "${remote_size}" "${LINE}"
-		fi
-	done < "${FILE}"
-done
+gluster volume list > /dev/null 2>&1 || die "'gluster' command unavailable"
+
+test "$#" -gt 0 || usage 'no volume specified'
+volume_is_valid "${1}" || die "invalid volume '${1}'"
+VOLUME="${1}"
+shift
+
+test "$#" -gt 0 || usage 'no remote node specified'
+REMOTE_HOST="${1}"
+shift
+
+if test "$#" -gt 0; then
+	test -d "${1}" || die "invalid directory '${1}'"
+	BACKUP_PREFIX="$1";shift
+fi
+
+LOCAL_PREFIX="$(brick_path "${VOLUME}" "${HOSTNAME}")"
+REMOTE_PREFIX="$(brick_path "${VOLUME}" "${REMOTE_HOST}")"
+
+gluster volume heal "${VOLUME}" info | vol_heal_list_gfid "${HOSTNAME}"| file_cmp "${LOCAL_PREFIX}" "${REMOTE_HOST}:${REMOTE_PREFIX}" ${BACKUP_PREFIX}
