Rework gfid2path to require the volume
 * Requiring the user specify the path to the brick we
   instead have them specify the volume and we figure out the brick path
   ourselves.

diff --git a/gluster-recovery b/gluster-recovery
--- a/gluster-recovery
+++ b/gluster-recovery
@@ -172,7 +172,7 @@ __usage()
 	(cmp|compare)
 		echo "usage: $0 ${__usage_progname} <volume> [<node>[:</path/to/brick>]]";;
 	(gfid2path)
-		echo "usage: $0 ${__usage_progname} </path/to/brick> <gfid> [<gfid> ...]";;
+		echo "usage: $0 ${__usage_progname} <volume> <gfid> [<gfid> ...]";;
 	(path2gfid)
 		echo "usage: $0 ${__usage_progname} </path/to/file> [...]";;
 	(*) sed -e 's/^	//' <<END_OF_USAGE
@@ -181,7 +181,7 @@ __usage()
 	  list			List files which need fixing.
 	  compare		Compare files between nodes.
 	  gfid2path		Find the file(s) for a given gfid.
-	  path2gfid		Find the gfid for listed file(s).
+	  path2gfid		Find the gfid for the given file(s).
 	  help			Display help about a command.
 
 	Report bugs at http://github.com/major0/glusterfs-recovery/issues
@@ -255,6 +255,7 @@ brick_path()
 # @1 brick path
 # @2 inum
 inum2path() {
+	: "inum2path($*)"
 	find "${1}" -inum "${2}" ! -path '*/.glusterfs/*'| \
 		while read inum2path_line; do
 			printf '%s\n' "${inum2path_line#${1}}"
@@ -271,6 +272,7 @@ inum2path() {
 #   IF: The GFID identifies a file, then this file is a hard-link to the actual file.
 gfid2path()
 {
+	: "gfid2path($*)"
 	set -- "${1}" "${2}" "${2%${2##????}}"
 	set -- "${1}" "${2}" "${1}/.glusterfs/${3%??}/${3#??}"
 	set -- "$@" "${3}/${2}"
@@ -296,6 +298,7 @@ gfid2path()
 # 'trusted.gfid'
 path2gfid()
 {
+	: "path2gfid($*)"
 	set -- "$(getfattr -e hex -n trusted.gfid "${1}" 2>/dev/null|sed -e '/^#/d')"
 	set -- "${1#trusted.gfid=0x}"
 	set -- "${@}" "$(printf '%.8s' "${1}")"
@@ -475,7 +478,7 @@ while getopts ':h' __arg; do
 		case "${1}" in
 		(--help)
 			OPTARG="$(__optarg "${1}" "${2}")"
-			test -z "${OPTARG}" || __doc "${OPTARG}"
+			test -z "${OPTARG}" || __usagusage "${OPTARG}"
 			__usage "${0}"; exit 0;;
 
 		##
@@ -560,9 +563,17 @@ case "${COMMAND}" in
 	;;
 
 (gfid2path)
-	test "$#" -gt '0' || __usage "${COMMAND}" 'no brick specified'
-	BRICK="${1}";shift
-	test "$#" -gt '1' || __usage "${COMMAND}" 'no gfid specified'
+	gluster volume list > /dev/null 2>&1 || die "'gluster' command unavailable"
+	test "$#" -gt '0' || __usage "${COMMAND}" 'no volume specified'
+	volume_is_valid "${1}" || die "invalid volume '${1}'"
+	VOLUME="${1}"
+	shift
+
+	if ! BRICK="$(brick_path "${VOLUME}" "${HOSTNAME}")"; then
+		die "local node not a member of volume '${VOLUME}'"
+	fi
+
+	test "$#" -ge '1' || __usage "${COMMAND}" 'no gfid specified'
 	for GFID; do
 		gfid2path "${BRICK}" "${GFID}"
 	done
